## Introduzione

Il gruppo Tufano gestisce diversi punti vendita Euronics. L'obiettivo di questo documento è di delineare la strategia tecnica per miglirare la gestione dell'attività. In particolare la richiesta è di realizzare un sitema che possa supportare i processi di business. In particolare:
  - **Otimizzazione prezzi al publico**: con l'obiettivo di massimizzare marginalità o quota di mercato in funzione del contesto competitivo.
  - **Pianificazione acquisti e scorte**: per minimizzare rotture di stock (_out of stock_) ed evitare giacenze inutilizzate, ottimizzando quindi la circolazione di capitale.
  - **Allocazione presso i punti vendita**: gestire la distribuzione dei prodotti verso i vari punti vendita in base alla domanda attesa e tenendo conto dei vincoli logistici.
  - **Competitors Intelligence**: per consentire reazioni tempestive ed adeguate a manovre della concorrenza (es. prezzi anomali finalizzati ad azzerare la disponibilità di determinati prodotti.)

### Indicatori di raggiungimento obiettivo

Al fine di meglio delineare la strategia tecnica e di misurare il rendimento del sistema ogetto di questo documento, è necessario fissare dei parametri di rendimento misurabili.
- +Xpp sul margine lordo per categorie chiave di prodotto entro.
